// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtxBnwKkEeIGxO9ulZjFh2BaaUCWbrL9E',
    appId: '1:1012523625550:web:2e01d8fa0135190e51a71f',
    messagingSenderId: '1012523625550',
    projectId: 'rakt-daata',
    authDomain: 'rakt-daata.firebaseapp.com',
    storageBucket: 'rakt-daata.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT_zIkvWUfkba6MrrwgykebLeLwMTmOC4',
    appId: '1:1012523625550:android:424a76361430d87951a71f',
    messagingSenderId: '1012523625550',
    projectId: 'rakt-daata',
    storageBucket: 'rakt-daata.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxH9pUQ23X00Pa-4-TBgtka5-d92pPk-U',
    appId: '1:1012523625550:ios:239ef14e5caf4ce551a71f',
    messagingSenderId: '1012523625550',
    projectId: 'rakt-daata',
    storageBucket: 'rakt-daata.appspot.com',
    iosBundleId: 'com.example.raktdataApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxH9pUQ23X00Pa-4-TBgtka5-d92pPk-U',
    appId: '1:1012523625550:ios:039b720a8cebaf1051a71f',
    messagingSenderId: '1012523625550',
    projectId: 'rakt-daata',
    storageBucket: 'rakt-daata.appspot.com',
    iosBundleId: 'com.example.raktdataApp.RunnerTests',
  );
}
